[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:8080 --workers 2 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8080"
